//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class activities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public activities()
        {
            this.activity_champions = new HashSet<activity_champions>();
        }
    
        public int activity_id { get; set; }
        public string activity_title { get; set; }
        public int event_id { get; set; }
        public byte day_number { get; set; }
        public System.TimeSpan start_time { get; set; }
        public Nullable<int> moderator_id { get; set; }
        public Nullable<int> first_jury_id { get; set; }
        public Nullable<int> second_jury_id { get; set; }
        public Nullable<int> third_jury_id { get; set; }
        public Nullable<int> fourth_jury_id { get; set; }
        public Nullable<int> fifth_jury_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity_champions> activity_champions { get; set; }
        public virtual events events { get; set; }
        public virtual jury jury { get; set; }
        public virtual jury jury1 { get; set; }
        public virtual jury jury2 { get; set; }
        public virtual moderators moderators { get; set; }
        public virtual jury jury3 { get; set; }
        public virtual jury jury4 { get; set; }
    }
}
