//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_champions
    {
        public int id { get; set; }
        public int activity_id { get; set; }
        public int champion_id { get; set; }
    
        public virtual activities activities { get; set; }
        public virtual members members { get; set; }
    }
}
