//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conferenceEntities : DbContext
    {
        private static conferenceEntities _context;
        public conferenceEntities()
            : base("name=conferenceEntities")
        {
        }

        public static conferenceEntities GetContext()
        {
            if (_context == null)
            {
                _context = new conferenceEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<activity_champions> activity_champions { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<jury> jury { get; set; }
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<moderators> moderators { get; set; }
        public virtual DbSet<sponsors> sponsors { get; set; }
    }
}
