//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class sponsors
    {
        public int sponsor_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string patronymic { get; set; }
        public string email_address { get; set; }
        public System.DateTime birthday { get; set; }
        public int country { get; set; }
        public string phone_number { get; set; }
        public string password { get; set; }
        public string photo_path { get; set; }
        public string gender { get; set; }
    
        public virtual countries countries { get; set; }
    }
}
